"""add_market_tables

Revision ID: 0b81b016ed14
Revises: 7d7cfe271917
Create Date: 2026-06-24 20:18:29.423406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b81b016ed14'
down_revision: Union[str, Sequence[str], None] = '7d7cfe271917'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_breadth',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('board', sa.String(length=16), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('up_count', sa.Integer(), nullable=False),
    sa.Column('down_count', sa.Integer(), nullable=False),
    sa.Column('flat_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('board', 'trade_date', name='uk_breadth_board_date')
    )
    op.create_index(op.f('ix_market_breadth_board'), 'market_breadth', ['board'], unique=False)
    op.create_table('market_index',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('change', sa.Float(), nullable=False),
    sa.Column('change_pct', sa.Float(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'trade_date', name='uk_idx_code_date')
    )
    op.create_index(op.f('ix_market_index_code'), 'market_index', ['code'], unique=False)
    op.create_table('sector_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('change_pct', sa.Float(), nullable=False),
    sa.Column('leading_stock', sa.String(length=64), nullable=True),
    sa.Column('leading_stock_change', sa.Float(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'trade_date', name='uk_sector_code_date')
    )
    op.create_index(op.f('ix_sector_data_code'), 'sector_data', ['code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sector_data_code'), table_name='sector_data')
    op.drop_table('sector_data')
    op.drop_index(op.f('ix_market_index_code'), table_name='market_index')
    op.drop_table('market_index')
    op.drop_index(op.f('ix_market_breadth_board'), table_name='market_breadth')
    op.drop_table('market_breadth')
    # ### end Alembic commands ###
