"""add_fk_to_daily_kline

Revision ID: 7d7cfe271917
Revises: 96372ef24a0f
Create Date: 2026-06-24 06:27:26.288800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d7cfe271917'
down_revision: Union[str, Sequence[str], None] = '96372ef24a0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'daily_kline', 'stocks', ['stock_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'daily_kline', type_='foreignkey')
    # ### end Alembic commands ###
