"""add_market_turnover

Revision ID: b5e3d8837265
Revises: a8fbc87af476
Create Date: 2026-06-24 21:02:03.444034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5e3d8837265'
down_revision: Union[str, Sequence[str], None] = 'a8fbc87af476'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_turnover',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('total_volume', sa.BigInteger(), nullable=False),
    sa.Column('stock_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trade_date', name='uk_turnover_date')
    )
    op.create_index(op.f('ix_market_turnover_trade_date'), 'market_turnover', ['trade_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_market_turnover_trade_date'), table_name='market_turnover')
    op.drop_table('market_turnover')
    # ### end Alembic commands ###
